// File: lib/firebase_options.dart
// Generated by AI Coding Agent - PSX Vision Pro
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyFakeApiKeyHere_ForCompilation_Success',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'psx-vision-pro-firebase',
    authDomain: 'psx-vision-pro-firebase.firebaseapp.com',
    storageBucket: 'psx-vision-pro-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyFakeApiKeyHere_ForCompilation_Success',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'psx-vision-pro-firebase',
    storageBucket: 'psx-vision-pro-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyFakeApiKeyHere_ForCompilation_Success',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'psx-vision-pro-firebase',
    storageBucket: 'psx-vision-pro-firebase.appspot.com',
    iosBundleId: 'com.psxvision.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyFakeApiKeyHere_ForCompilation_Success',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'psx-vision-pro-firebase',
    storageBucket: 'psx-vision-pro-firebase.appspot.com',
    iosBundleId: 'com.psxvision.pro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyFakeApiKeyHere_ForCompilation_Success',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'psx-vision-pro-firebase',
    authDomain: 'psx-vision-pro-firebase.firebaseapp.com',
    storageBucket: 'psx-vision-pro-firebase.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyFakeApiKeyHere_ForCompilation_Success',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'psx-vision-pro-firebase',
    authDomain: 'psx-vision-pro-firebase.firebaseapp.com',
    storageBucket: 'psx-vision-pro-firebase.appspot.com',
  );
}
